### PR TITLE
Update composer.json

### PR DESCRIPTION
**Pull request by startupz**

### CODE REVIEW

**Comment by romainneutron** [comment]
Why this change ? version are case insensitive.

BTW, doctrine release is uppercase, see https://packagist.org/packages/doctrine/mongodb-odm

**Comment by startupz** [comment]
Problem 1
    - neutron/mongo-odm-silex-provider 0.1.1 requires doctrine/mongodb-odm >=1.0.0-beta4 -> no matching package found.
    - neutron/mongo-odm-silex-provider 0.1.0 requires doctrine/mongodb-odm >=1.0.0-beta4 -> no matching package found.
    - Installation request for neutron/mongo-odm-silex-provider \* -> satisfiable by neutron/mongo-odm-silex-provider[0.1.0, 0.1.1].

So ... What this ?

**Comment by startupz** [comment]
https://github.com/doctrine/mongodb-odm/tree/1.0.0-BETA4

**Comment by romainneutron** [comment]
It's probably a `minimum-stability` issue in your configuration. As doctrine mongodb odm has no stable releases yet, you should either allow beta packages to be installed in your composer.json, either explicitely require `doctrine/mongodb-odm` in your composer.json, see http://getcomposer.org/doc/04-schema.md#minimum-stability

**Comment by romainneutron** [comment]
does it solve your issue ?

**Comment by startupz** [comment]
Ok ... Sorry about that. I'm in a new project and i forgot this ...

Thanks a lot !

**Pull request closed without merging**
